version: "3.6"
services:

  runner:
    image: registry.webrunners.de/webrunners/infrastructure/gitlab-runner-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DISABLE_SELFUPDATE  # Disable selfupdate service with default-config, stack-named secret and volumes. [default: yes]
      - EXECUTOR  # docker|shell [default: shell]
      - OPTIONS  # Additional gitlab-runner options
      - TAG_LIST  # Comma separated list of GitLab runner tags
      - TOKEN  # Provide CI_SERVER_TOKEN as variable. Unsecure
      - URL  # Provide CI_SERVER_URL. Possibly provided by default config
      - VOLUMES  # SELFUPDATE only: Comma separated list of volumes, that will be simple mounted like volumename:/volumename
      - URL_CONFIG=${URL_CONFIG:-CI_SERVER_URL}  # Disabled SELFUPDATE only: Name of the config that contains the CI_SERVER_URL only
      - TOKEN_SECRET  # Disabled SELFUPDATE only: Name of the secret that contains the CI_SERVER_TOKEN only
    deploy:
      replicas: 1
    configs:
      - source: CI_SERVER_URL
        target: /${URL_CONFIG:-CI_SERVER_URL}
    secrets:
      - source: CI_SERVER_TOKEN
        target: /run/secrets/${TOKEN_SECRET}

configs:
  # <CI_SERVER_URL from GitLabCI Runner settings>
  CI_SERVER_URL:
    external: true
    name: ${URL_CONFIG:-CI_SERVER_URL}

secrets:
  # <Token from GitLabCI Runner settings>
  CI_SERVER_TOKEN:
    external: true
    name: ${TOKEN_SECRET}
